@startuml

class Ship {
    - shipName : String
    - yearBuilt : String
    + getShipName() : String
    + setShipName(shipName : String) : void
    + getYearBuilt() : String
    + setYearBuilt(yearBuilt : String) : void
    + toString() : String
    + printShip() : void
}

class CruiseShip extends Ship {
    - maxNumberPassengers : int
    + getMaxNumberPassengers() : int
    + setMaxNumberPassengers(maxNumberPassengers : int) : void
    + toString() : String
}

@enduml